export default ({
    ADD:'ADD',
    DELETE:'DELETE',
    ON_QUANTITY_ADD:'ON_QUANTITY_ADD',
    ON_QUANTITY_REMOVE:'ON_QUANTITY_REMOVE',
    TOTAL_PRICE:'TOTAL_PRICE',
    ISLOGIN:'ISLOGIN',
    LOGIN:"LOGIN",
    ONLOGOUT:'ONLOGOUT',
    ONOTPVERIFY:'ONOTPVERIFY'

    
    
})